"""add page sections

Revision ID: 18762925a39f
Revises: 0d99cbb2bd7e
Create Date: 2026-09-11 15:58:37.170711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18762925a39f'
down_revision: Union[str, None] = '0d99cbb2bd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_sections_page'), 'page_sections', ['page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_sections_page'), table_name='page_sections')
    op.drop_table('page_sections')
    # ### end Alembic commands ###
