"""add site settings and order shipping cost

Revision ID: 4ef6e0f43bc3
Revises: 18762925a39f
Create Date: 2026-09-11 20:51:48.592895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef6e0f43bc3'
down_revision: Union[str, None] = '18762925a39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('accent_color', sa.String(), nullable=False),
    sa.Column('font_pairing', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('shipping_cost', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default='0': orders ya puede tener filas reales en producción
    # (el flujo de pago ya se probó de punta a punta) y la columna es NOT NULL.
    op.add_column('orders', sa.Column('shipping_cost', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_cost')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
