"""add product notes, replace fixed notes fields

Revision ID: c7f4fbc2677e
Revises: 4ef6e0f43bc3
Create Date: 2026-09-12 16:15:24.308012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f4fbc2677e'
down_revision: Union[str, None] = '4ef6e0f43bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# De más suave (arriba) a más fuerte (abajo) — misma escala que ya usa el
# resto del sitio, para que el backfill no se vea desentonado.
_DEFAULT_COLORS = ['#E3CCA1', '#CB9F4E', '#6A501F']  # gold-200, gold-500, gold-800

_products_table = sa.table(
    'products',
    sa.column('id', sa.Integer),
    sa.column('notes_top', sa.String),
    sa.column('notes_heart', sa.String),
    sa.column('notes_base', sa.String),
)
_product_notes_table = sa.table(
    'product_notes',
    sa.column('id', sa.Integer),
    sa.column('product_id', sa.Integer),
    sa.column('name', sa.String),
    sa.column('color', sa.String),
    sa.column('position', sa.Integer),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Backfill: cada producto con notes_top/heart/base no vacío pasa a filas
    # individuales en product_notes, mismo orden, para no perder contenido real.
    connection = op.get_bind()
    rows = connection.execute(
        sa.select(_products_table.c.id, _products_table.c.notes_top, _products_table.c.notes_heart, _products_table.c.notes_base)
    ).fetchall()
    inserts = []
    for row in rows:
        for value, color in zip([row.notes_top, row.notes_heart, row.notes_base], _DEFAULT_COLORS):
            if value:
                inserts.append({'product_id': row.id, 'name': value, 'color': color, 'position': len([i for i in inserts if i['product_id'] == row.id])})
    if inserts:
        op.bulk_insert(_product_notes_table, inserts)

    op.drop_column('products', 'notes_top')
    op.drop_column('products', 'notes_heart')
    op.drop_column('products', 'notes_base')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('notes_base', sa.VARCHAR(), nullable=True))
    op.add_column('products', sa.Column('notes_heart', sa.VARCHAR(), nullable=True))
    op.add_column('products', sa.Column('notes_top', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###

    # Mejor esfuerzo, no perfectamente simétrico: solo recupera las primeras 3
    # notas por posición (salida/corazón/fondo) y pierde el color y cualquier
    # nota extra — la migración de vuelta original tampoco tenía color.
    connection = op.get_bind()
    rows = connection.execute(
        sa.select(_product_notes_table.c.product_id, _product_notes_table.c.name, _product_notes_table.c.position)
        .order_by(_product_notes_table.c.product_id, _product_notes_table.c.position)
    ).fetchall()
    by_product: dict[int, list[str]] = {}
    for row in rows:
        by_product.setdefault(row.product_id, []).append(row.name)
    for product_id, names in by_product.items():
        values = (names + [None, None, None])[:3]
        connection.execute(
            _products_table.update()
            .where(_products_table.c.id == product_id)
            .values(notes_top=values[0], notes_heart=values[1], notes_base=values[2])
        )

    op.drop_table('product_notes')
