"""add product variants for decants

Revision ID: ddc7d92b42df
Revises: f3c840f3125d
Create Date: 2026-09-11 00:35:50.235625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc7d92b42df'
down_revision: Union[str, None] = 'f3c840f3125d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_ml', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # batch mode: SQLite no soporta ALTER TABLE ADD CONSTRAINT fuera de una
    # estrategia de copiar-y-mover; batch_alter_table la aplica solo en SQLite
    # y en Postgres emite el ALTER TABLE normal.
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.add_column(sa.Column('product_variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_ml', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_order_items_product_variant_id_product_variants',
            'product_variants', ['product_variant_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.drop_constraint('fk_order_items_product_variant_id_product_variants', type_='foreignkey')
        batch_op.drop_column('size_ml')
        batch_op.drop_column('product_variant_id')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
