"""add key/is_builtin to page_sections and page_section_history

Revision ID: edf994ac09bc
Revises: c7f4fbc2677e
Create Date: 2026-09-14 21:04:04.334077

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf994ac09bc'
down_revision: Union[str, None] = 'c7f4fbc2677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_page_sections_table = sa.table(
    'page_sections',
    sa.column('id', sa.Integer),
    sa.column('page', sa.String),
    sa.column('type', sa.String),
    sa.column('position', sa.Integer),
    sa.column('is_active', sa.Boolean),
    sa.column('content', sa.JSON),
    sa.column('key', sa.String),
    sa.column('is_builtin', sa.Boolean),
    sa.column('created_at', sa.DateTime),
)

# Copy exacto de lo que hoy vive hardcodeado en cada HTML — el seed no debe
# cambiar nada visible, solo mover ese texto a una fila editable.
_BUILTIN_SECTIONS = [
    {
        'page': 'home', 'key': 'home_recent_heading', 'type': 'section_heading', 'position': 0,
        'content': {'heading': 'Recién llegados'},
    },
    {
        'page': 'home', 'key': 'home_decant_callout', 'type': 'decant_callout', 'position': 1,
        'content': {
            'heading': 'Antes de llevar el frasco completo',
            'body': 'Pide un decant: el mismo perfume original, fraccionado en un frasco de prueba de 5ml o 10ml. Disponible en los perfumes que lo tengan activo en su ficha.',
            'cta_label': 'Ver catálogo',
            'cta_link': '/catalogo.html',
            'rows': [
                {'label': '5 ml', 'value': 'Para probar antes de decidir'},
                {'label': '10 ml', 'value': 'Para llevar contigo sin comprometerte al frasco'},
                {'label': 'Origen', 'value': 'El mismo perfume, nunca una imitación'},
            ],
        },
    },
    {
        'page': 'home', 'key': 'home_manifesto', 'type': 'manifesto', 'position': 2,
        'content': {
            'items': [
                {'heading': 'Frascos originales', 'text': 'Sin réplicas, sin imitaciones. Cada frasco es el original de la casa que lo produce.'},
                {'heading': 'Ficha completa', 'text': 'Notas de salida, corazón y fondo, concentración y duración estimada en cada producto.'},
                {'heading': 'Pago como prefieras', 'text': 'Tarjeta, PSE, Nequi o Bancolombia, sin salir del sitio.'},
            ],
        },
    },
    {
        'page': 'catalogo', 'key': 'catalogo_header', 'type': 'section_heading', 'position': 0,
        'content': {'heading': 'Catálogo'},
    },
    {
        'page': 'producto', 'key': 'producto_related_heading', 'type': 'section_heading', 'position': 0,
        'content': {'heading': 'También te puede interesar'},
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_section_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_section_history_page'), 'page_section_history', ['page'], unique=False)
    op.add_column('page_sections', sa.Column('key', sa.String(), nullable=True))
    # server_default='0': page_sections ya puede tener filas reales en producción
    # (el editor de secciones ya está en uso) y la columna es NOT NULL.
    op.add_column('page_sections', sa.Column('is_builtin', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_page_sections_key'), 'page_sections', ['key'], unique=False)
    # ### end Alembic commands ###

    # Seed: las 5 secciones "fijas" que se vuelven editables pasan a ser filas
    # reales, con exactamente el copy que ya estaba hardcodeado — no cambia
    # nada visible, solo lo hace editable/ocultable/borrable desde el panel.
    connection = op.get_bind()
    now = datetime.now(timezone.utc)
    connection.execute(
        _page_sections_table.insert(),
        [
            {
                'page': s['page'], 'type': s['type'], 'position': s['position'],
                'is_active': True, 'content': s['content'], 'key': s['key'], 'is_builtin': True,
                'created_at': now,
            }
            for s in _BUILTIN_SECTIONS
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()
    connection.execute(
        _page_sections_table.delete().where(
            _page_sections_table.c.key.in_([s['key'] for s in _BUILTIN_SECTIONS])
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_sections_key'), table_name='page_sections')
    op.drop_column('page_sections', 'is_builtin')
    op.drop_column('page_sections', 'key')
    op.drop_index(op.f('ix_page_section_history_page'), table_name='page_section_history')
    op.drop_table('page_section_history')
    # ### end Alembic commands ###
